# -*- coding: utf-8 -*-
"""ICA10_Kati Johnson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fy84Y5GDZv8GIZq9JbgKhLZ2k4YkX6ap
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

"""

*   Please read titanic.csv from the DATA folder
*   Change 1s to "Survived" under the Survived column of the data frame by looking at the example provided.
*   Get rows which don't have "?" under Pclass column and move to the next step.


 """

titanic = pd.read_csv('/content/drive/MyDrive/CSC302/DATA/titanic.csv')
titanic.loc[titanic["Survived"] == 1, "Survived"] = "Survived"
titanic.loc[titanic["Survived"] == 0, "Survived"] = "Dead"
titanic = titanic.loc[titanic["Pclass"] != "?"]
titanic["Pclass"] = pd.to_numeric(titanic["Pclass"])
titanic.head(10)
titanic.dtypes

"""Create a multipanel plot which draws density plots for each class-survived combination. Please also use the hue parameter based on the Sex attribute to have two density plots in each panel with different colors."""

fig = plt.figure()
g = sns.FacetGrid(titanic, col="Pclass",  row="Survived", hue='Sex',palette="cubehelix")
g.map(sns.kdeplot, "Age",fill=True)

#you can uncomment below when you come up with your density plots for each class-survived combination
titles = ['Died in Class 1','Died in Class 2', 'Died in Class 3', 'Survived in Class 1','Survived in Class 2', 'Survived in Class 3']
for ax,title in zip(g.axes.flatten(),titles):
     ax.set_title(title )

